server:
  port: 8082
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductManagement
    username: postgres
    password: 5071
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format-sql: true
      hibernate:
        ddl_auto: update
      show_sql: true