server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT my_key, my_value FROM my_properties WHERE application=? and profile=? and label=?
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_74ab49c9900fb12
    username: bff903c40e035b
    password: 51f4fe10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: jdbc
